### ISSUE TITLE
Support URI datatype

### ISSUE THREAD

**Issue by joepio** [ontola/atomic-server#1024]
We have a [URI datatype in the docs](https://atomicdata.dev/datatypes/uri), but it's not in the implementations.

## TODO

- [x] rust Value + Datatype
- [x] js Value + Datatype
- [x] browser ontology editor
- [x] browser validation in form
- [ ] browser table editor
- [x] browser preview (render as `a href`)
