### ISSUE TITLE
Atomic-Server video

### ISSUE THREAD

**Issue by joepio** [ontola/atomic-server#902]
Audience: software engineers looking for an open source data modelling / CMS tool

## Set-up

- Overview
- Introduce Atomic Data
- Introduce Atomic Server
- Demo 
  - Set up server (docker)
  - Make data model
  - Make table
  - Make issues
  - Reuse in typescript / react

## ToDo

- [x] Set up YouTube channel [DONE](https://www.youtube.com/@Atomic-Server)
- [ ] Set up Twitter / X / Mastodon account 
- [ ] Other socials?
- [ ] Write video script / improve set up aobve
- [ ] Shoot video
- [ ] Edit video
- [ ] Publish to socials

**Comment by joepio** [comment]
https://github.com/user-attachments/assets/4310ad43-2595-4cf8-b336-fb8bcc692e79

**Comment by joepio** [comment]
https://github.com/user-attachments/assets/32e82de5-11ca-4c2e-8c25-b293d79f6023
